### ISSUE TITLE
全面支持 aa

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#323]
controller、service 等都已经支持 async function 了，现在 egg 核心中剩下各处中间件的改造，插件现阶段不适合进行改造。

- [x] egg 加载的中间件。
- [x] router 中引入的中间件。
- [x] 应用自行通过 `app.use(mw)` 引入的中间件。
- [x] schedule 插件（现在应该是支持的，需要增加测试用例保证）。https://github.com/eggjs/egg-schedule/pull/13
- [x] multipart 插件。https://github.com/eggjs/egg-multipart/pull/3
- [x] 集成 aa 的测试用例。#339
- [x] ctx.curl 和 app.curl 的支持 #342 
- [x] render 相关方法的支持 #343 
- [x] 如何在 egg 中使用 aa 的文档 #349

**Comment by fengmk2** [comment]
>  应用自行通过 app.use(mw) 引入的中间件。

还允许这样引入么？

**Comment by dead-horse** [comment]
现在没有地方禁止这个用法。这个好解决，我们可以统一在 app.use 处封装。不过 router 比较麻烦一点，还要考虑后续我们是否要跟进 koa-router。

**Comment by dead-horse** [comment]
集成到 egg 中的插件也需要支持 aa，multipart 比较难搞，除非我们用 co 包一层。

**Comment by atian25** [comment]
现在 egg 不能直接用 koa 的插件吧, 都要包一层, 是不是 1.0 版本的中间件都直接支持 ctx 的方式就好了?

**Comment by popomore** [comment]
还是向下兼容吧，在 loader 改也可以，app.use 感觉不应该被使用，用了也搞不清楚顺序。
TZ | 天猪 <notifications@github.com>于2017年2月7日 周二12:02写道：

**Comment by dead-horse** [comment]
没有地方推荐用户直接用 app.use，但是现在确实是可以被使用的。

现在准备支持 `async function(ctx, next)` 和 `function*(next)` 两种形式。

**Comment by gxcsoccer** [comment]
@dead-horse 现在对 aa 的支持是在 koa 里实现的还是 egg 里？

**Comment by jtyjty99999** [comment]
感觉co.wrap包一层也不是很麻烦吧

**Comment by dead-horse** [comment]
在 egg 里，底层还是用 generator function 这套，将 aa 包成 generator function。等到后面我们大规模往 aa 迁移了，再考虑底层用 aa。

**Comment by popomore** [comment]
router 我们已经 wrap 过了，现在就支持了吧？

**Comment by gxcsoccer** [comment]
感觉就 multipart 麻烦点

**Comment by popomore** [comment]
我来写这个，改 hacknews 的时候发现有问题再来提 https://github.com/eggjs/egg/issues/276

**Comment by popomore** [comment]
multipart 是指用 co-busboy 么

**Comment by fengmk2** [comment]
multipart 用 co 包一下即可。

**Comment by dead-horse** [comment]
egg-core 我先将标题里面发现的这些点先补上。

**Comment by dead-horse** [comment]
https://github.com/nodejs/node/pull/11185

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-core/pull/50

**Comment by dead-horse** [comment]
现在底层还是基于 generator 来支持 aa 的，所以 aa 的性能会受一点影响。 @popomore 写文档的时候还是要说明一下，现阶段还是推荐用 generator？

**Comment by atian25** [comment]
@popomore 现在插件中的 middleware 是不是都改为新的方式

**Comment by popomore** [comment]
generator 现在性能会好点，不改吧
TZ | 天猪 <notifications@github.com>于2017年2月8日 周三09:32写道：

**Comment by dead-horse** [comment]
@atian25 现在 7.x 支持 async await 了，所以 egg 也开始基于 generator 开启对 aa 的支持，等到 LTS 版本支持 aa 的时候，我们再切换到 koa@2，然后迁移代码。不然现在写了就没法在 6.x 用了。

**Comment by arden** [comment]
node下个版本 7.6 应该会默认支持aa了，koa2正式版那就应该很快了。

**Comment by atian25** [comment]
@arden https://eggjs.org/zh-cn/intro/egg-and-koa.html#升级计划 这里有讲到.

koa 的核心开发者中好几个就在 egg 这边, 所以不用担心.

**Comment by Rwing** [comment]
@arden 跑个题，7.6默认支持aa这个消息的来源是？

**Comment by dead-horse** [comment]
@Rwing https://github.com/nodejs/node/pull/11185 node 7.6 会将 v8 升级到 5.5，届时就默认支持 aa 了，但是要等到 v8 5.6 才会对它进行性能优化。

**Comment by Rwing** [comment]
@dead-horse good job！我以为大版本号才会对V8进行升级，竟然7.6就升级了，多谢

**Comment by dead-horse** [comment]
7.x 是开发分支，所以上面经常会有 breaking change

**Comment by fengmk2** [comment]
@dead-horse 这个不算 breaking change，所以还是发了 7.x

**Comment by dead-horse** [comment]
恩，land 到 7.x 上的时候是做了向前兼容的。 https://github.com/nodejs/node/pull/11029

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg/pull/339

**Comment by atian25** [comment]
这个应该做完了, close 了

**Comment by arden** [comment]
koa 2.0 已经正式发布了。
