### ISSUE TITLE
documents optimization

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#354]
now we received some feedback and realized lots of features are undocumented.

- [x] 404 configuration #352  @dead-horse
- [x] session #353  @dead-horse
- [x] pm2 #345  @shaoshuai0102  https://github.com/eggjs/egg/pull/370
- [x] tutorials index #359 @atian25 
- [x] split `plugin` docs to `plugin` and `plugin-development`
- [ ] add egg-static document
- [x] multiple processes introduction @dead-horse

**Comment by popomore** [comment]
We can add an index page for tutorials, replacing mysql now. It contains a list for some normal case like db access, session, react...

**Comment by atian25** [comment]
build-in middleware also need docs

**Comment by shaoshuai0102** [comment]
https://github.com/eggjs/egg/pull/370

**Comment by atian25** [comment]
- how to define special loader rule
- deployment

**Comment by popomore** [comment]
document for app.beforeClose

**Comment by atian25** [comment]
env document missing `default` description

**Comment by atian25** [comment]
document about github workflow

**Comment by atian25** [comment]
- [ ] split `plugin` docs to `plugin` and `plugin-development`
- [ ] add egg-static document

**Comment by popomore** [comment]
https://github.com/eggjs/doctools

**Comment by popomore** [comment]
- [ ] generate build-in plugin document
- [ ] test document
